"""Regenerate docs/corpus-missing-originals.md from the v3 failures list, the manifests, and the Sept 1 package.

    .venv/Scripts/python.exe scripts/build_missing_doc.py
Run after any download pass (the downloader rewrites corpus/manifests/v3_downloads/failures.csv).
"""
import csv
import re
import sys
from collections import Counter
from datetime import date
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
MAN = ROOT / "corpus" / "manifests"
OUT = ROOT / "docs" / "corpus-missing-originals.md"
NL = chr(10)


def slug(row, i):
    bits = [row.get(k, "") for k in ("filer", "counterparty", "buyer", "vendor", "source_venue", "parties", "doc_type")]
    s = re.sub(r"[^A-Za-z0-9]+", "_", "_".join(b for b in bits if b))[:80].strip("_") or "doc"
    return f"{i:03d}_{s}"


def ext_of(url):
    m = re.search(r"\.(pdf|htm|html|docx?|xlsx?|zip|txt)(?:$|\?)", url.lower())
    return "." + m.group(1) if m else ".bin"


def esc(s):
    return (s or "").replace("|", "\\|").replace(NL, " ")


# Sept 1 package originals still missing: checked by file presence beside download_originals.sh
SEPT1 = [
    ("US_GSA_MAS_ConstellationWest_pricelist_54151S_2025_ORIGINAL.PDF",
     "https://www.gsaadvantage.gov/ref_text/47QTCA25D007E/109Z4I.3W0BZ6_47QTCA25D007E_47QTCA25D007E-3-28-2025-377665.PDF",
     "404", "GSA MAS price list, Constellation West, SIN 54151S, 2025. URL gone; search GSA eLibrary for contract 47QTCA25D007E."),
    ("MI_DTMB_Deloitte_MiIntegrate_Contract_SOW_Rates_2013-2026_ORIGINAL.pdf",
     "https://www.michigan.gov/dtmb/-/media/Project/Websites/dtmb/Procurement/Contracts/006/180000000078.pdf",
     "403", "Michigan DTMB contract 180000000078 (Deloitte, MiIntegrate). M2's named second thin-thread document."),
    ("deep2_MI_DTMB_Accenture_ITTraining_Contract_2025_MA250000000723_ORIGINAL.pdf",
     "https://www.michigan.gov/dtmb/-/media/Project/Websites/dtmb/Procurement/Contracts/MiDEAL/002/250000000723.pdf",
     "403", "Michigan DTMB MiDEAL contract 250000000723 (Accenture, IT training, 2025)."),
]
sept1_missing = [s for s in SEPT1 if not (ROOT / "corpus" / "twm_corpus" / s[0]).exists()]
sept1_total = 48

failures = {}
fp = MAN / "v3_downloads" / "failures.csv"
if fp.exists():
    for r in csv.DictReader(open(fp, encoding="utf-8")):
        failures[r["url"].strip()] = r["error"]

rows = []
for folder in ("v3_edgar", "v3_gov", "v3_invoices"):
    for i, r in enumerate(csv.DictReader(open(MAN / folder / "manifest.csv", encoding="utf-8")), 1):
        url = (r.get("url") or "").strip()
        if url in failures:
            err = failures[url]
            m = re.search(r"HTTP Error (\d+)", err)
            code = m.group(1) if m else ("error page" if "error page" in err else "conn reset")
            who = " / ".join(x for x in (r.get("filer"), r.get("counterparty"), r.get("buyer"), r.get("vendor"), r.get("parties")) if x)
            rows.append(dict(folder=folder, dest=slug(r, i) + ext_of(url), who=who, doc_type=r.get("doc_type", ""),
                             date=r.get("filing_date") or r.get("date_vintage") or r.get("date") or "", url=url, code=code,
                             host=urlparse(url).netloc, notes=(r.get("notes") or "")[:120]))

by_host = Counter(r["host"] for r in rows)
L = ["# Corpus originals still to retrieve", "",
     f"**Status as of:** {date.today().isoformat()} · **Owner:** Kyle (manual browser download) · regenerated by `scripts/build_missing_doc.py`", "",
     "Every file below refused scripted download (HTTP 403/404) and needs a real browser. Drop retrieved files into `corpus/inbox/` with any name; "
     "Claude files them, re-runs the downloader, and regenerates this list.", "",
     "## Totals", "", "| Set | Fetched | Missing |", "|---|---|---|",
     f"| Corpus v3 (388 URLs) | {388 - len(rows)} | {len(rows)} |",
     f"| Sept 1 package ({sept1_total} URLs) | {sept1_total - len(sept1_missing)} | {len(sept1_missing)} |", ""]
if by_host:
    L.append("**Missing v3 by site:** " + ", ".join(f"{h} ({n})" for h, n in by_host.most_common()) + NL)
L += [f"## 1. Sept 1 package ({len(sept1_missing)})", "", "| Save as (beside `corpus/twm_corpus/download_originals.sh`) | URL | Error | Notes |", "|---|---|---|---|"]
for name, url, code, note in sept1_missing:
    L.append(f"| `{name}` | {url} | {code} | {esc(note)} |")
L += ["", f"## 2. Corpus v3 ({len(rows)})", ""]
for folder, title in (("v3_gov", "Government contracts"), ("v3_edgar", "EDGAR filings"), ("v3_invoices", "Invoices and timesheets")):
    sub = [r for r in rows if r["folder"] == folder]
    if not sub:
        continue
    L += [f"### {title} — `{folder}` ({len(sub)})", "", "| Save as (in `v3_downloads/" + folder + "/`) | Parties | Doc type | Date | URL | Error | Manifest notes |", "|---|---|---|---|---|---|---|"]
    for r in sub:
        L.append(f"| `{r['dest']}` | {esc(r['who'])} | {esc(r['doc_type'])} | {esc(r['date'])} | {r['url']} | {r['code']} | {esc(r['notes'])} |")
    L.append("")
OUT.write_text(NL.join(L) + NL, encoding="utf-8")
print(f"wrote {OUT.name}: {len(rows)} v3 + {len(sept1_missing)} Sept 1 still missing")
